<?php
require('header.php');
require('sub_header.php');
require('page_1.php');
require('hire.php');
require('choose_opt.php');
require('save_page.php');
require('trending_01.php');
require('trending_02.php');
require('footer.php');
?>